apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ur79nodu6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ur79nodu6-java-springboot-gitops